### ISSUE TITLE
Many FutureWarning: max_iter and tol parameters added to class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'

### ISSUE THREAD

**Issue by david-a-wheeler** [ageron/handson-ml#150] opened 2017-12-30 18:05 UTC
Hi, I'm walking through your book "Hands-on Machine Learning with Scikit-Learn & TensorFlow" which I got for Christmas.

A number of the Jupyter notebook steps produce warnings on Python 3.6 and latest PyPI packages.  E.g., in 03_classification, the input:

~~~~python
from sklearn.linear_model import SGDClassifier
sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(X_train, y_train_5)
~~~~

Produces this warning message:

~~~~
/usr/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
~~~~

I would expect there to be no warning messages.

Thanks!

**Comment by ageron** [comment] 2018-01-11 20:32
Hi David,
Thanks for your feedback.  The code in the book was written using a previous version of Scikit-Learn in which the warning did not appear (0.18).  I did not update the notebook because I prefer to have the book and the notebooks remain as close as possible, so people don't get too confused.  The warning message is very clear, so I expect people will know what to do (e.g., explicitly set max_iter=1000).
That said, I will eventually (as soon as I have a bit of time), update the notebook and add a comment to explain why the notebook is different from the book.
If you want to submit a PR I'd be happy to merge it.  :)
I hope you're enjoying the book!
Cheers,
Aurélien

**Comment by ageron** [comment] 2018-03-15 22:29
Duplicate of #90

**Closed by ageron** 2018-03-15 22:29 UTC
