### ISSUE TITLE
Can't import MultiOutputMixin in Linear Regression

### ISSUE THREAD

**Issue by maagalamharsha** [ageron/handson-ml#493] opened 2019-10-02 11:55 UTC
Hi 
I was trying to run the linear regression model that is given in chapter 2. But I am getting this `cannot import name 'MultiOutputMixin'` error. 

Can someone help me out with that. I have written my code in Azure Notebooks(its basically a jupyter notebook)

Here is the code:

```python
from sklearn.linear_model import LinearRegression, MultiOutputMixin # ERROR
from sklearn.linear_model.base import MultiOutputMixin

lin_reg=LinearRegression()

lin_reg.fit(housing_prepared,housing_labels)
```

```
Error:
_ImportError                               Traceback (most recent call last)
<ipython-input-160-d0c0f15ef49e> in <module>
----> 1 from sklearn.linear_model import LinearRegression,MultiOutputMixin
      2 from sklearn.linear_model.base import MultiOutputMixin
      3 
      4 lin_reg=LinearRegression()
      5 

~/anaconda3_501/lib/python3.6/site-packages/sklearn/linear_model/__init__.py in <module>
     10 # complete documentation.
     11 
---> 12 from .base import LinearRegression
     13 
     14 from .bayes import BayesianRidge, ARDRegression

~/anaconda3_501/lib/python3.6/site-packages/sklearn/linear_model/base.py in <module>
     25 
     26 from ..utils._joblib import Parallel, delayed
---> 27 from ..base import (BaseEstimator, ClassifierMixin, RegressorMixin,
     28                     MultiOutputMixin)
     29 from ..utils import check_array, check_X_y

ImportError: cannot import name 'MultiOutputMixin'_
```

Thank you

**Comment by ageron** [comment] 2019-10-05 05:26
Hi @maagalamharsha ,

I'm not sure where you got this code, but I don't use `MultiOutputMixin` anywhere in my book, so you can replace the first two lines with this:

```python
from sklearn.linear_model import LinearRegression
```

That said, if this still does not work, then I recommend quitting Python or Jupyter, reinstall Scikit-Learn (latest version) and start again. There may be something wrong with your installation.
Hope this helps.

**Comment by maagalamharsha** [comment] 2019-10-15 11:31
> Hi @maagalamharsha ,
> 
> I'm not sure where you got this code, but I don't use `MultiOutputMixin` anywhere in my book, so you can replace the first two lines with this:
> 
> ```python
> from sklearn.linear_model import LinearRegression
> ```
> 
> That said, if this still does not work, then I recommend quitting Python or Jupyter, reinstall Scikit-Learn (latest version) and start again. There may be something wrong with your installation.
> 
> Hope this helps.

Hi @ageron ,
This issue has been resolved by restarting the kernel. Even I was wondering why I got that `MultiOutputMixin` error. I resolved it long ago sorry for the delayed response. Thank you

**Comment by ageron** [comment] 2019-10-16 03:08
Thanks for your feedback @maagalamharsha , I'm glad the problem is solved, closing this issue.

**Closed by ageron** 2019-10-16 03:08 UTC

**Comment by nandita96** [comment] 2021-05-03 19:00
> > Hi @maagalamharsha ,
> > I'm not sure where you got this code, but I don't use `MultiOutputMixin` anywhere in my book, so you can replace the first two lines with this:
> > ```python
> > from sklearn.linear_model import LinearRegression
> > ```
> > 
> > 
> > That said, if this still does not work, then I recommend quitting Python or Jupyter, reinstall Scikit-Learn (latest version) and start again. There may be something wrong with your installation.
> > Hope this helps.
> 
> Hi @ageron ,
> This issue has been resolved by restarting the kernel. Even I was wondering why I got that `MultiOutputMixin` error. I resolved it long ago sorry for the delayed response. Thank you

thank you for your this information.
i also faced the same issue.... please " restart" the kernel . 
then it will work .. :)
