### ISSUE TITLE
Chapter 3 - Classification

### ISSUE THREAD

**Issue by dgcarvalhorp** [ageron/handson-ml#616] opened 2021-01-31 01:00 UTC
this error happens when trying to view the instance

![image](https://user-images.githubusercontent.com/48815190/106371710-43b92600-6346-11eb-99da-16e1967d2452.png)

**Comment by shuntksh** [comment] 2021-02-12 17:17
Having a similar issue on the first code example of Chapter 3 (2nd Ed Page 86). Instead of setting index, I had to change it to `X.iloc[idx]` and `some_digit.values.reshape()` to get it work.

``
# There are 70,000 images, eadh image has 784 features (28x28 pixel)
import matplotlib as mpl
import matplotlib.pyplot as plt

some_digit = X.iloc[0]
some_digit_image = some_digit.values.reshape(28,28)

plt.imshow(some_digit_image, cmap="binary")
plt.axis("off")
plt.show()
```

**Comment by ageron** [comment] 2021-03-10 23:34
Thanks for your feedback. This issue was caused by the fact that Scikit-Learn changed `fetch_openml()` in version 0.24 to return Pandas DataFrames by default instead of NumPy arrays. I fixed this by setting `as_frame=False` when calling `fetch_openml()`. Please `git pull` to get the latest code, and try again, everything should work fine now.
Closing this issue, but feel free to reopen this issue if the problem persists.

**Closed by ageron** 2021-03-10 23:34 UTC
