### ISSUE TITLE
Code Hangs on line in Chapter 3

### ISSUE THREAD

**Issue by oxbits** [ageron/handson-ml#5] opened 2017-03-05 21:19 UTC
This line in Chapter 3:

y_train_knn_pred = cross_val_predict(knn_clf, X_train, y_train, cv=3)

is causing my system to hang.

macOS Sierra 10.12.3 (16D32)

Python:
3.6.0 (default, Dec 30 2016, 15:26:50) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
jupyter-client==4.4.0
jupyter-core==4.3.0

* update: checked and ensured that I have the latest version of everything, still the same issue

**Comment by ageron** [comment] 2017-03-06 07:04
@oxbits That's odd. Can you try training on a small subset of the training set? Just replace X_train and y_train with X_train[:50] and y_train[:50].

**Comment by ageron** [comment] 2017-04-02 21:53
Hi @oxbits, any news on this issue?  I tried reproducing it, but everything works fine for me.  Did you try with a smaller dataset?

**Comment by ageron** [comment] 2017-04-07 19:50
Closing this issue since I cannot reproduce it.  Please reopen if you still experience the problem and you have run the tests above.

**Closed by ageron** 2017-04-07 19:50 UTC

**Comment by StephenOman** [comment] 2017-08-18 09:59
Hi @ageron - I thought I had this problem too, but it seems that algorithm takes a while to run on a MacBook compared to the previous examples. Throughout the chapter, the learning algorithms are pretty fast, taking at most a few minutes. But that cross-val KNN took my machine about 50 minutes to run.

**Comment by ageron** [comment] 2017-09-18 07:17
Thanks for your feedback @StephenOman , I added a warning just before that cell.
