### ISSUE TITLE
Math_linear_algebra is really, really slow

### ISSUE THREAD

**Issue by ewosborne** [ageron/handson-ml#10] opened 2017-04-17 12:01 UTC
Not sure if this is a bug or it's just the way things are.  The linear algebra notebook is incredibly slow to render and to scroll through.  I suspect it's getting bogged down on rendering the equations.  I've tried it on two different computers using IE, Edge, and Opera.  Edge sometimes just crashes.  Opera runs the notebook but poorly.

Let me know if there's any debug info I should gather.

**Comment by ageron** [comment] 2017-04-17 14:32
Hi @ewosborne, thanks for your feedback.  Unfortunately, I can't reproduce the problem: everything runs smoothly on my laptop (and I also tried on an old 2006 Ubuntu desktop, so it does not seem to be a CPU issue).  This particular notebook has many math equations, which Jupyter renders using the [MathJax](https://www.mathjax.org/) javascript library. Perhaps there is some Jupyter configuration option activated that makes MathJax generate images on the fly or something...

Do you see a difference when reading the notebook using the following viewers?

* [Jupyter's viewer](http://nbviewer.jupyter.org/github/ageron/handson-ml/blob/master/math_linear_algebra.ipynb) (which uses MathJax)
* or [github's viewer](https://github.com/ageron/handson-ml/blob/master/math_linear_algebra.ipynb)
(which converts the equations to images on the server side).

If it is a Jupyter/MathJax issue, then the latter should not be a problem.  However, github renders the equations rather poorly.

I hope this helps.

**Comment by ewosborne** [comment] 2017-04-17 16:01
@ageron Thanks for getting back to me.
I don't know much about this stuff but I suspet it's a MathJax issue.  Jupyter's viewer is slow but not as slow as the one I'm running my notebooks on (a personal server).  I also notice that when I run my personal server I get lots of error messages like "File failed to load:http://<server>:8888/static/components/MathJax/....BasicLatin.js".  And there is no BasicLatin.js anywhere in the view I synced up to from github.  

Maybe part of my problem is that I'm missing some magical javascript somehow?

If you send me your email address I can unicast you login to my Jupyter server if you want to take a look.

**Comment by ageron** [comment] 2017-04-17 16:10
@ewosborne It seems that this may be a Debian packaging issue, check out the last comments of:
https://github.com/jupyter/notebook/issues/1108
One solution is to install the Jupyter using `pip` rather than debian's `apt-get`.
Another option is to copy the missing javascript files to the right location.
Hope this helps!

Since the bug is not due to these Jupyter notebooks, I'm closing this issue.

**Closed by ageron** 2017-04-17 16:10 UTC
