### ISSUE TITLE
chapter 3 mnist classification

### ISSUE THREAD

**Issue by jasonjoe2019** [ageron/handson-ml#504] opened 2019-10-24 03:22 UTC
I got a error,

```The number of classes has to be greater than one;got 1 class.```

when I run the following code.

```python
from sklearn.linear_model import SGDClassifier

sgd_clf = SGDClassifier(max_iter=5, tol=-np.infty, random_state=42)
sgd_clf.fit(X_train, y_train_5)
```

**Comment by ageron** [comment] 2019-10-24 04:25
Hi @jasonjoe2019 ,

Thanks for your question. The error message tells you that all the instances in the dataset belong to the same class. This means that `y_train_5` contains a single value, possible repeated multiple times. Perhaps it's 0, perhaps it's 1. Try printing `y_train_5` to see what's wrong with it. Double check the code that created it.

I recommend verifying that your code is exactly identical to the one in the notebook at https://github.com/ageron/handson-ml/blob/master/03_classification.ipynb
In particular, make sure all the cells up to cell 16 are identical.

Hope this helps.

**Comment by jasonjoe2019** [comment] 2019-10-25 13:36
thanks a lot!

**Comment by jasonjoe2019** [comment] 2019-10-25 13:47
I think there is error in the cell 16, y_train_5 is supposed to y_train, is it right?

**Comment by ageron** [comment] 2019-10-27 20:15
Hi @jasonjoe2019 ,
Good question! No, the cell is correct: the goal is to train a binary classifier first (in this case a "5-detector", which only tries to detect whether or not an image represents a 5), and then later in the notebook we will train a multiclass classifier, capable of classifying all 10 digits.
Hope this helps!

**Comment by jasonjoe2019** [comment] 2019-10-29 01:13
Thanks for your reply!
it works after I update the input[15]:
y_train_5 = (y_train == 5) to y_train_5 = (y_train == '5')
y_test_5 = (y_test == 5) to y_test_5 = (y_test == '5')

**Comment by xhw180230** [comment] 2019-12-07 13:32
Hi~You are right.Because it is string('5') instead of numerical(5) which store in y_train.So will get False all if y_train==5

**Comment by ageron** [comment] 2019-12-16 15:21
Looks like the problem is solved. Thanks for your feedback. I'll close the issue, but feel free to reopen it if the problem is not actually resolved.

**Closed by ageron** 2019-12-16 15:21 UTC

**Comment by Sachin67-Rock** [comment] 2021-01-19 05:53
i got a error when i am doing like this
y_train_5 = y_train == '5'
y_test_5 = y_test == '5'
It showing error :- 
ValueError: y should be a 1d array, got an array of shape () instead.
and when I am writing without string it shows me false.

**Comment by Sachin67-Rock** [comment] 2021-01-19 06:18
The Error is solved.
