### ISSUE TITLE
Chapter 2: stratified sampling error

### ISSUE THREAD

**Issue by jorgelmadrid** [ageron/handson-ml#395] opened 2019-04-04 03:23 UTC
While doing stratified sampling based on the income category with Scikit-Learn’s `StratifiedShuffleSplit` class, I found that implementing this code will result in an error:

`housing['income_cat'] = pd.cut(housing['median_income'], bins=[0., 1.5, 3.0, 4.5, 6., np.inf], 
                               labels=[1, 2, 3, 4, 5])`

Error:

`Object of type 'CategoricalDtype' has no len()`

I fixed it by changing the dtype to `'float64'`:

`housing['income_cat'] = housing['income_cat'].astype('float64')`

**Comment by ageron** [comment] 2019-04-04 11:29
Hi @jorgelmadrid ,
Thanks for your feedback. I believe this is a duplicate of #385. This is most likely due to a bug in Scikit-Learn 0.20.0 and 0.20.1 (resolved in scikit-learn/scikit-learn#12706), so if you have one of these versions, please update to the latest version of Scikit-Learn.

**Closed** 2019-04-05 18:41 UTC
