### ISSUE TITLE
Chapter 2, Transformation pipelines

### ISSUE THREAD

**Issue by dizhu1991** [ageron/handson-ml#135] opened 2017-12-01 01:58 UTC
Hi Aurélien, 

Thanks for the wonderful book! I am trying to go through it, and am now stuck at Chapter 2, page 66. I put your code of the pipelines in Jupyter notebook, and there is an error.

```python
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

num_pipeline = Pipeline([
    ('imputer', Imputer(strategy="median")),
    ('attribs_adder', CombinedAttributesAdder()),
    ('std_scaler', StandardScaler()),
])

housing_num_tr = num_pipeline.fit_transform(housing_num)
```

The error is:

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-70-1af98a8f0d76> in <module>()
      8 ])
      9 
---> 10 housing_num_tr = num_pipeline.fit_transform(housing_num)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/pipeline.py in fit_transform(self, X, y, **fit_params)
    279         """
    280         last_step = self._final_estimator
--> 281         Xt, fit_params = self._fit(X, y, **fit_params)
    282         if hasattr(last_step, 'fit_transform'):
    283             return last_step.fit_transform(Xt, y, **fit_params)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/pipeline.py in _fit(self, X, y, **fit_params)
    211                 Xt, fitted_transformer = fit_transform_one_cached(
    212                     cloned_transformer, None, Xt, y,
--> 213                     **fit_params_steps[name])
    214                 # Replace the transformer of the step with the fitted
    215                 # transformer. This is necessary when loading the transformer

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/externals/joblib/memory.py in __call__(self, *args, **kwargs)
    360 
    361     def __call__(self, *args, **kwargs):
--> 362         return self.func(*args, **kwargs)
    363 
    364     def call_and_shelve(self, *args, **kwargs):

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/pipeline.py in _fit_transform_one(transformer, weight, X, y, **fit_params)
    579                        **fit_params):
    580     if hasattr(transformer, 'fit_transform'):
--> 581         res = transformer.fit_transform(X, y, **fit_params)
    582     else:
    583         res = transformer.fit(X, y, **fit_params).transform(X)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/base.py in fit_transform(self, X, y, **fit_params)
    515         if y is None:
    516             # fit method of arity 1 (unsupervised transformation)
--> 517             return self.fit(X, **fit_params).transform(X)
    518         else:
    519             # fit method of arity 2 (supervised transformation)

<ipython-input-62-2052cdb5aae0> in transform(self, X, y)
      7         rooms_per_household = X[:,rooms_ix]/X[:,household_ix]
      8         population_per_household = X[:,population_ix]/X[:,household_ix]
----> 9         if self.add_bedrooms_per_room:
     10             bedrooms_per_room = X[:, bedrooms_ix]/X[:, rooms_ix]
     11             return np.c_[X, rooms_per_household, population_per_household, bedrooms_per_room]

AttributeError: 'CombinedAttributesAdder' object has no attribute 'add_bedrooms_per_room'
```

I didn't know how to fix it. What does this mean? Could you give me a hint?

Thanks,

Di

**Comment by ageron** [comment] 2017-12-08 02:45
Hi @dizhu1991 ,
I'm glad you enjoy the book.  The bug you are getting is quite weird. It says that the `CombinedAttributesAdder` class has no attribute `add_bedrooms_per_room`, but when I look at the code in the [Jupyter notebook](https://github.com/ageron/handson-ml/blob/master/02_end_to_end_machine_learning_project.ipynb), cell In [68], I see that this attribute does get initialized in the constructor (the `__init__()` method):

```python
class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
    def __init__(self, add_bedrooms_per_room = True): # no *args or **kargs
        self.add_bedrooms_per_room = add_bedrooms_per_room
    def fit(self, X, y=None):
        return self  # nothing else to do
    def transform(self, X, y=None):
        rooms_per_household = X[:, rooms_ix] / X[:, household_ix]
        population_per_household = X[:, population_ix] / X[:, household_ix]
        if self.add_bedrooms_per_room:
            bedrooms_per_room = X[:, bedrooms_ix] / X[:, rooms_ix]
            return np.c_[X, rooms_per_household, population_per_household,
                         bedrooms_per_room]
        else:
            return np.c_[X, rooms_per_household, population_per_household]
```

So I don't really see how this can happen.  Are you using the exact same Jupyter notebook or did you copy code into a new notebook?  Can you make sure that it's the exact same code and restart and run all the cells in the notebook?  I think the first printed edition of the book had a typo, it said `add_bedroom_per_room' or something like that, but I fixed it a long time ago. If you are copying from the book and you have that initial version, then it might explain the problem. If so, try using the Jupyter notebooks from this github project instead, these typos are fixed here.

Hope this help.

**Comment by ageron** [comment] 2018-03-15 22:21
I hope everything ended up working.  I'll close this issue, please reopen it if the problem is not fixed.

**Closed by ageron** 2018-03-15 22:21 UTC

**Comment by races1986** [comment] 2018-05-19 20:40
I found the same issue, not sure if it was fixed or not. 

`class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
    def __int__(self, add_bedrooms_per_room=True): #no *args or **kargs
        self.add_bedrooms_per_room = add_bedrooms_per_room
    def fit(self, X, y=None):
        return self #nothing else to do
    def transform(self, X, y=None):
        rooms_per_household = X[:,rooms_ix] / X[:,household_ix]
        population_per_household = X[:,population_ix] / X[:,household_ix]
        if self.add_bedrooms_per_room:
            bedrooms_per_room = X[:,bedrooms_ix] / X[:,rooms_ix]
            return np.c_[X, rooms_per_household, population_per_household, bedrooms_per_room]
        else:
            return np.c_[X, rooms_per_household, population_per_household]`

`attr_adder = CombinedAttributesAdder(add_bedrooms_per_room=False)
housing_extra_attribs = attr_adder.transform(housing.values)`

And the output: 
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-88-f7fa3b83bd2d> in <module>()
      1 attr_adder = CombinedAttributesAdder() #add_bedrooms_per_room=False
----> 2 housing_extra_attribs = attr_adder.transform(housing.values)

<ipython-input-87-625e587a771d> in transform(self, X, y)
      7         rooms_per_household = X[:,rooms_ix] / X[:,household_ix]
      8         population_per_household = X[:,population_ix] / X[:,household_ix]
----> 9         if self.add_bedrooms_per_room:
     10             bedrooms_per_room = X[:,bedrooms_ix] / X[:,rooms_ix]
     11             return np.c_[X, rooms_per_household, population_per_household, bedrooms_per_room]

AttributeError: 'CombinedAttributesAdder' object has no attribute 'add_bedrooms_per_room'`

Sorry.... not sure how to format this correctly.

**Comment by Shalsh23** [comment] 2019-03-19 05:26
I am getting the exact same error.

The code I ran is this (which is basically the example from the book) - 
```
from sklearn.base import BaseEstimator, TransformerMixin

rooms_ix, bedrooms_ix, population_ix, household_ix = 3, 4, 5, 6

class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
    def _init_(self, add_bedrooms_per_room = True):
        self.add_bedrooms_per_room = add_bedrooms_per_room
    def fit(self, X, y=None):
        return self
    def transform(self, X, y=None):
        rooms_per_household = X[:, population_ix]/X[:, household_ix]
        population_per_household = X[:, population_ix]/X[:, household_ix]
        if self.add_bedrooms_per_room:
            bedrooms_per_room = X[:, bedrooms_ix]/X[:, rooms_ix]
            return np.c_[X, rooms_per_household, population_per_household, bedrooms_per_room]
        else:
            return np.c_[X, rooms_per_household, population_per_household]
        
        attr_adder = CombinedAttributesAdder(add_bedrooms_per_room=False)
        housing_extra_attribs = attr_adder.transform(housing.values)

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

num_pipeline = Pipeline([('imputer', Imputer(strategy="median")), ('attribs_adder', CombinedAttributesAdder()), ('std_scaler', StandardScaler()),])

housing_num_tr = num_pipeline.fit(housing_num)
```

and the error I got -
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-107-ca71157e70a7> in <module>()
      4 num_pipeline = Pipeline([('imputer', Imputer(strategy="median")), ('attribs_adder', CombinedAttributesAdder()), ('std_scaler', StandardScaler()),])
      5 
----> 6 housing_num_tr = num_pipeline.fit(housing_num)

/opt/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py in fit(self, X, y, **fit_params)
    246             This estimator
    247         """
--> 248         Xt, fit_params = self._fit(X, y, **fit_params)
    249         if self._final_estimator is not None:
    250             self._final_estimator.fit(Xt, y, **fit_params)

/opt/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py in _fit(self, X, y, **fit_params)
    211                 Xt, fitted_transformer = fit_transform_one_cached(
    212                     cloned_transformer, None, Xt, y,
--> 213                     **fit_params_steps[name])
    214                 # Replace the transformer of the step with the fitted
    215                 # transformer. This is necessary when loading the transformer

/opt/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/memory.py in __call__(self, *args, **kwargs)
    360 
    361     def __call__(self, *args, **kwargs):
--> 362         return self.func(*args, **kwargs)
    363 
    364     def call_and_shelve(self, *args, **kwargs):

/opt/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py in _fit_transform_one(transformer, weight, X, y, **fit_params)
    579                        **fit_params):
    580     if hasattr(transformer, 'fit_transform'):
--> 581         res = transformer.fit_transform(X, y, **fit_params)
    582     else:
    583         res = transformer.fit(X, y, **fit_params).transform(X)

/opt/anaconda3/lib/python3.6/site-packages/sklearn/base.py in fit_transform(self, X, y, **fit_params)
    515         if y is None:
    516             # fit method of arity 1 (unsupervised transformation)
--> 517             return self.fit(X, **fit_params).transform(X)
    518         else:
    519             # fit method of arity 2 (supervised transformation)

<ipython-input-103-dab83b9d46d9> in transform(self, X, y)
     11         rooms_per_household = X[:, population_ix]/X[:, household_ix]
     12         population_per_household = X[:, population_ix]/X[:, household_ix]
---> 13         if self.add_bedrooms_per_room:
     14             bedrooms_per_room = X[:, bedrooms_ix]/X[:, rooms_ix]
     15             return np.c_[X, rooms_per_household, population_per_household, bedrooms_per_room]

AttributeError: 'CombinedAttributesAdder' object has no attribute 'add_bedrooms_per_room'
```

I would really appreciate any pointers on how to resolve this. Thanks!

**Comment by ageron** [comment] 2019-03-19 06:34
Hi @Shalsh23 ,
Thanks for your question. Your constructor is called `_init_()`, it should be called `__init__` (with four underscores instead of two), or else it will be a regular method, not the constructor, so Python will not call it when you create an instance, and therefore the attributes will not be initialized properly, hence the bug.
In general, when you see a bug like this, I recommend you try debugging, either using a Python debugger, or by printing some debug information at various points where you expect the code to go, for example print variable values to see if they actually have the value you expect. In this example, if you had printed some debug info in the constructor, you would have noticed that the constructor was never called.
I hope this helps, and you enjoy the book! :)

**Comment by Shalsh23** [comment] 2019-03-27 21:54
Thanks for your help @ageron !!

**Comment by soutog** [comment] 2020-09-12 01:09
@ageron I am getting this ValueError. And I don't know what to do
could you help me?


from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

num_pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy="median")),
        ('attribs_adder', CombinedAttributesAdder()),
        ('std_scaler', StandardScaler()),
    ])

housing_num_tr = num_pipeline.fit_transform(housing_num)




---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-62-77eb93b23e4c> in <module>
      8     ])
      9 
---> 10 housing_num_tr = num_pipeline.fit_transform(housing_num)

~/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py in fit_transform(self, X, y, **fit_params)
    383         """
    384         last_step = self._final_estimator
--> 385         Xt, fit_params = self._fit(X, y, **fit_params)
    386         with _print_elapsed_time('Pipeline',
    387                                  self._log_message(len(self.steps) - 1)):

~/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py in _fit(self, X, y, **fit_params)
    313                 message_clsname='Pipeline',
    314                 message=self._log_message(step_idx),
--> 315                 **fit_params_steps[name])
    316             # Replace the transformer of the step with the fitted
    317             # transformer. This is necessary when loading the transformer

~/anaconda3/lib/python3.7/site-packages/joblib/memory.py in __call__(self, *args, **kwargs)
    353 
    354     def __call__(self, *args, **kwargs):
--> 355         return self.func(*args, **kwargs)
    356 
    357     def call_and_shelve(self, *args, **kwargs):

~/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py in _fit_transform_one(transformer, X, y, weight, message_clsname, message, **fit_params)
    726     with _print_elapsed_time(message_clsname, message):
    727         if hasattr(transformer, 'fit_transform'):
--> 728             res = transformer.fit_transform(X, y, **fit_params)
    729         else:
    730             res = transformer.fit(X, y, **fit_params).transform(X)

~/anaconda3/lib/python3.7/site-packages/sklearn/base.py in fit_transform(self, X, y, **fit_params)
    569         if y is None:
    570             # fit method of arity 1 (unsupervised transformation)
--> 571             return self.fit(X, **fit_params).transform(X)
    572         else:
    573             # fit method of arity 2 (supervised transformation)

<ipython-input-52-9f6315b5a73e> in transform(self, X, y)
     15         population_per_household = X[:, population_ix] / X[:, households_ix]
     16         if self.add_bedrooms_per_room:
---> 17             bedrooms_per_room = X[:, bedrooms_ix] / X[:rooms_ix]
     18             return np.c_[X, rooms_per_household, population_per_household, bedrooms_per_room]
     19         else:

ValueError: operands could not be broadcast together with shapes (16512,) (3,8)

**Comment by MatiBigTuna** [comment] 2021-09-19 23:06
@soutog  Could you fix the ValueError? I have the same problem

**Comment by ageron** [comment] 2021-09-21 03:22
Looking at the stacktrace, the `ValueError` exception occurs on this line:

```python
bedrooms_per_room = X[:, bedrooms_ix] / X[:rooms_ix]
```

This is not exactly the code written in the book. Here is the correct code:

```python
bedrooms_per_room = X[:, bedrooms_ix] / X[:, rooms_ix]
```

Notice that it's `X[:, rooms_ix]`, not `X[:rooms_ix]`. The comma is important. `X[:, rooms_ix]` means "get all rows from column 3 (rooms_ix), while `X[:rooms_ix]` means "get all rows up to (but excluding) row 3 (rooms_ix), and implicitly get all columns (all 8 of them)". That's why the second array had a shape equal to (3, 8), which was incompatible with the shape of the first array (16512,).

If you run into an error in the code, please check that you have the exact same code as in the book. If the problem persists, then check that the code in the Jupyter notebook (if I find a mistake in the book, I cannot fix the paper copies that were already printed, but I can fix the notebooks online).

Hope this helps!

**Comment by leticiagcsilva** [comment] 2022-08-12 02:06
I resolved the error by passing a method 
 ```
num_pipeline = Pipeline(
    steps=[("imputer", SimpleImputer(strategy="median")), ("scaler", StandardScaler())]))
```
for _num_pipeline_ it was not defined. I believe we can use any of the three options that are presented in the _Cleaning the Data_ section.
