### ISSUE TITLE
Chapter 2: SSLCertVerificationError and URLError

### ISSUE THREAD

**Issue by awrd2019** [ageron/handson-ml#361] opened 2019-02-22 22:56 UTC
Hi,

After running this to make the function to load the data for the housing project:
import os
import tarfile
from six.moves import urllib

DOWNLOAD_ROOT = "https://raw.githubusercontent.com/ageron/handson-ml/master/"
HOUSING_PATH = os.path.join("datasets", "housing")
HOUSING_URL = DOWNLOAD_ROOT + "datasets/housing/housing.tgz"

def fetch_housing_data(housing_url=HOUSING_URL, housing_path=HOUSING_PATH):
    if not os.path.isdir(housing_path):
        os.makedirs(housing_path)
    tgz_path = os.path.join(housing_path, "housing.tgz")
    urllib.request.urlretrieve(housing_url, tgz_path)
    housing_tgz = tarfile.open(tgz_path)
    housing_tgz.extractall(path=housing_path)
    housing_tgz.close()

I then ran fetch_housing_data() and got two errors, the first:
SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)
and the second:
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>

I'm pretty sure I followed the book exactly in the setup of the jupyter notebook as well so I'm kind of stumped as to why this happened. Please help!

**Comment by ageron** [comment] 2019-02-23 08:25
Hi @awrd2019 ,
This is a Python 3.6 installation problem. Please see #339.
Hope this helps!

**Comment by ageron** [comment] 2019-02-23 08:26
duplicate of #339

**Closed by ageron** 2019-02-23 08:26 UTC

**Comment by awrd2019** [comment] 2019-02-25 14:48
Thanks so much! I really appreciate all your work and look forward to learning a lot.

**Comment by BigDataPlayers** [comment] 2019-11-17 03:26
installed python 3.7 through homebrew. Tried pip upgrade cer

**Comment by BigDataPlayers** [comment] 2019-11-17 03:27
downloaded python 3.8.1. Ran /Applications/Python\ 3.8/Install\ Certificates.command. No luck.

**Comment by ageron** [comment] 2019-11-20 11:06
Hi @BigDataPlayers ,

Thanks for your question. TensorFlow 2.0 does not support Python 3.8 yet, you must use Python 3.6 or 3.7. You already installed Python 3.7 with Homebrew, that's great: I believe it installs the appropriate certifi package for the SSL certificates, so it should work fine. In fact, I just tried installing Python 3.7 with HomeBrew and running the code above, and it worked like a charm.

To check, you can try running `/usr/local/bin/python3` (this is where HomeBrew installs Python 3 by default). Then copy/paste the code above (starting with `import os` up to `housing_tgz.close()`, and also don't forget to call `fetch_housing_data()` after that). If it works, then the problem is most likely that Jupyter is not running this version of Python (my guess is that it's running a version of Python downloaded from python.org, on which the certifi installation script was not run). In this case, to fix it you just need to run this command:

```
/usr/local/bin/python3 -m ipykernel install --user --name=python3
```

This will register this version of Python (version 3.7 from homebrew) as the default Python 3 kernel for Jupyter.

If you want to use virtualenv to create an isolated environment (recommended), then run this instead:

```
/usr/local/bin/python3 -m pip install --user -U pip wheels # upgrade pip
/usr/local/bin/python3 -m pip install --user -U virtualenv # install virtualenv
cd $HOME # or change to any other development directory you prefer
/usr/local/bin/python3 -m virtualenv env # create a virtual environment
source env/bin/activate # activate it
/usr/local/bin/python3 -m ipykernel install --user --name=python3 # register env to Jupyter
jupyter notebook # start jupyter
```

Hope this helps!
